2018-10-19 15:08:10,992 ERROR: Exception on /un_follow/wjj [GET] [in D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\PycharmProjects\FlaskWeb\app\routes.py", line 164, in un_follow
    current_user.un_follow(username)
  File "D:\PycharmProjects\FlaskWeb\app\models.py", line 64, in un_follow
    if self.is_following(user):
  File "D:\PycharmProjects\FlaskWeb\app\models.py", line 68, in is_following
    return self.followed.filter(followers.c.followed_id == user.id).count() > 0
AttributeError: 'str' object has no attribute 'id'
2018-10-19 15:19:06,295 INFO: Yuan_blog startup [in D:\PycharmProjects\FlaskWeb\app\__init__.py:58]
2018-10-19 15:42:19,034 INFO: Yuan_blog startup [in D:\PycharmProjects\FlaskWeb\app\__init__.py:58]
2018-10-19 15:42:56,162 ERROR: Exception on /un_follow/wjj [GET] [in D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\PycharmProjects\FlaskWeb\app\routes.py", line 164, in un_follow
    current_user.un_follow(username)
  File "D:\PycharmProjects\FlaskWeb\app\models.py", line 64, in un_follow
    if self.is_following(user):
  File "D:\PycharmProjects\FlaskWeb\app\models.py", line 68, in is_following
    return self.followed.filter(followers.c.followed_id == user.id).count() > 0
AttributeError: 'str' object has no attribute 'id'
2018-10-19 15:45:10,988 INFO: Yuan_blog startup [in D:\PycharmProjects\FlaskWeb\app\__init__.py:58]
2018-10-19 15:45:47,253 ERROR: Exception on /un_follow/wjj [GET] [in D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\PycharmProjects\FlaskWeb\app\routes.py", line 164, in un_follow
    current_user.unfollow(username)
  File "D:\PycharmProjects\FlaskWeb\app\models.py", line 64, in unfollow
    if self.is_following(user):
  File "D:\PycharmProjects\FlaskWeb\app\models.py", line 68, in is_following
    return self.followed.filter(followers.c.followed_id == user.id).count() > 0
AttributeError: 'str' object has no attribute 'id'
2018-10-19 15:50:34,085 ERROR: Exception on /un_follow/solo [GET] [in D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PycharmProjects\FlaskWeb\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\PycharmProjects\FlaskWeb\app\routes.py", line 164, in un_follow
    current_user.unfollow(username)
  File "D:\PycharmProjects\FlaskWeb\app\models.py", line 64, in unfollow
    if self.is_following(user):
  File "D:\PycharmProjects\FlaskWeb\app\models.py", line 68, in is_following
    return self.followed.filter(followers.c.followed_id == user.id).count() > 0
AttributeError: 'str' object has no attribute 'id'
2018-10-19 15:52:06,012 INFO: Yuan_blog startup [in D:\PycharmProjects\FlaskWeb\app\__init__.py:58]
